config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'

	scope "(:locale)", locale: /en|de/ do
		get 'position' => 'application#set_user_position'
		get 'imprint' => 'welcome#imprint'
		get 'about' => 'welcome#about'

		resources :products, module: :product, only: [:index]

		resources :feedbacks, only: [:new, :create]
		
		resources :companies, only: [:new, :create, :show], module: :company do
			resources :products
			get "confirm/:confirmation_token" => "companies#confirm", as: :confirm
			resources :password, only: [:update, :edit], controller: :password_reset, param: :reset_token
		end

		namespace :company, path: :companies do
			resources :sessions, only: [:new, :create]
			delete "sessions" => "sessions#destroy"
			resources :password, only: [:new], controller: :password_reset
			post 'password' => "password_reset#create", as: :password_reset_create
		end

		get ':id' => 'company/companies#show'
	end

	namespace 'api', defaults: { format: :json } do
		namespace 'v1' do
			resources :companies, module: :company, only: [:index, :show] do 
				resources :products, only: [:index, :show]
			end

			resources :products, module: :product, only: [:index]

			namespace :user, path: :users do
				resources :sessions, only: [:create]
				get 'session' => "sessions#show"
				resources :positions, only: [:index, :create, :show]
			end
		end

		namespace 'v2' do
			resources :companies, module: :company, only: [:index, :show] do 
				resources :products, only: [:index, :show]
			end

			resources :products, module: :product, only: [:index]

			namespace :user, path: :users do
				resources :sessions, only: [:create]
				get 'session' => "sessions#show"
				resources :positions, only: [:index, :create, :show]
			end
		end
	end

end

app/models/company.rb
class Company < ActiveRecord::Base
	include ActiveModel::Validations

	has_secure_password

	validates_presence_of [:name, :email, :password, :street, :zip_code, :locality, :vat_number, :longitude, :latitude, :phone_number]
	validates_uniqueness_of [:name, :email, :phone_number, :slug, :vat_number]
	
	validates :vat_number, valvat: { lookup: true }

	extend FriendlyId
	friendly_id :name, use: :slugged

	geocoded_by :address
	before_validation :geocode, if: ->(obj){ obj.address.present? and obj.street_changed? }

	has_many :products

	def address
		if street.present? && zip_code.present? && locality.present?
			[street, zip_code, locality].compact.join(', ')
		end
	end

	def product_publishing_remaining?
		if remaining_products.nil? || remaining_products > 0
			true
		else
			false
		end
	end

	def decrement_product_counter(nr = 1)
		if not remaining_products.nil?
			if remaining_products >= nr
				update(remaining_products: (remaining_products - nr))
			else
				false
			end
		end
	end

	def coordinates
		[latitude, longitude]
	end



	def confirmed?
		confirmation_token.blank?
	end

	def confirm
		update_attribute(:confirmation_token, nil)
	end

	def generate_confirmation_token
		self.confirmation_token = SecureRandom.urlsafe_base64
	end

	def generate_password_reset_token
		self.password_reset_token = SecureRandom.urlsafe_base64
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	before_save :set_long_lat

	reverse_geocoded_by :latitude, :longitude

	mount_uploader :product_picture, ProductPictureUploader

	belongs_to :company

	has_many :clothing_sizes

	validates_presence_of [:name, :product_picture]
	validates :order_link, url: { allow_blank: true }

	self.per_page = 10

	def price
		unless price_on_request
			if price_in_cent
				price_in_cent / 100.0
			end
		else
			nil
		end
	end

	def price=(amount)
		self.price_in_cent = amount.gsub(',', '.').to_d * 100.0
	end
	
	def price_on_request
		if price_in_cent.nil?
			true
		else
			false
		end
	end

	alias_method :price_on_request?, :price_on_request

	def price_on_request=(value)
		if value == true || value == "1"
			self.price_in_cent = nil
		end
	end
	
	STATUSES = [:active, :inactive]
	enum status: STATUSES

	private

	def set_long_lat
		unless self.longitude || self.latitude
			self.longitude = company.longitude
			self.latitude = company.latitude
		end
	end
end

app/controllers/api/v1/company/base.rb
class Api::V1::Company::Base < Api::V1::Base
	before_action :set_company

	protected

	def set_company
		@company = Company.includes(:products).find(params[:company_id] || params[:id])
	rescue ActiveRecord::RecordNotFound
		render json: { errors: ["Company not found"] }, status: 404

		return
	end
end

app/controllers/api/v1/company/companies_controller.rb
class Api::V1::Company::CompaniesController < Api::V1::Company::Base
	include Api::V1::User::SessionsHelper

	before_action :set_company, only: :show

	def index
		@user_session = find_user_session_by_token(params[:session_token])

		if @user_session && @user_session.coordinates
			@companies = Company.near(@user_session.coordinates, 5000).paginate(page: params[:page])
		else
			@companies = Company.all.paginate(page: params[:page])
		end
	end

	def show
	end
end

app/controllers/api/v1/company/products_controller.rb
class Api::V1::Company::ProductsController < Api::V1::Company::Base
	before_action :set_product, only: :show

	def index
		@products = @company.products.active
	end

	def show
	end

	private

	def set_product
		@product = @company.products.active.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		render json: { errors: ["Product not Found"] }, status: 404

		return
	end
end

app/controllers/api/v1/product/base.rb
class Api::V1::Product::Base < Api::V1::Base
end

app/controllers/api/v1/product/products_controller.rb
class Api::V1::Product::ProductsController < Api::V1::Product::Base
	include Api::V1::User::SessionsHelper

	def index
		@q = ::Product.active.includes(:company).ransack(params[:q])

		@user_session = find_user_session_by_token(params[:session_token])

		if params[:without_position] != "1" && @user_session && @user_session.coordinates
			@products = @q.result.near(@user_session.coordinates, 5000).paginate(page: params[:page])
		else
			@products = @q.result.paginate(page: params[:page])
		end
	end
end

app/controllers/api/v2/company/base.rb
class Api::V2::Company::Base < Api::V2::Base
	before_action :set_company

	protected

	def set_company
		@company = Company.includes(:products).find(params[:company_id] || params[:id])
	rescue ActiveRecord::RecordNotFound
		render json: {
			error: {
				type: "COMPANY_NOT_FOUND"
			}
		}, status: 404

		return
	end
end

app/controllers/api/v2/company/companies_controller.rb
class Api::V2::Company::CompaniesController < Api::V2::Company::Base
	before_action :set_company, only: :show

	def index
		if coordinates = @user_session.coordinates
			@companies = Company.near(coordinates, 5000).paginate(page: params[:page])
		else
			@companies = Company.all.paginate(page: params[:page])
		end
	end

	def show
	end
end

app/controllers/api/v2/company/products_controller.rb
class Api::V2::Company::ProductsController < Api::V2::Company::Base
	before_action :set_product, only: :show

	def index
		@products = @company.products.active
	end

	def show
	end

	private

	def set_product
		@product = @company.products.active.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		render json: {
			error: {
				type: "PRODUCT_NOT_FOUND"
			}
		}, status: 404

		return
	end
end

app/controllers/api/v2/product/base.rb
class Api::V2::Product::Base < Api::V2::Base
end

app/controllers/api/v2/product/products_controller.rb
class Api::V2::Product::ProductsController < Api::V2::Product::Base
	def index
		@q = ::Product.active.includes(:company).ransack(name_cont: params[:search])

		if coordinates = @user_session.coordinates
			@products = @q.result.near(coordinates, 5000).paginate(page: params[:page])
		else
			@products = @q.result.paginate(page: params[:page])
		end
	end
end

app/controllers/company/api/companies_controller.rb
class Company::Api::CompaniesController < Company::Base
	before_action :set_company, only: :show

	def index
		@companies = Company.all

		render json: @companies
	end

	def show
		render json: @company
	end
end

app/controllers/company/api/products_controller.rb
class Company::Api::ProductsController < Company::Base
	before_action :set_product, only: :show

	def index
		@products = @company.products

		render json: @products
	end

	def show
		render json: @product
	end

	private

	def set_product
		@product = @company.products.find(params[:id])
	rescue ActiveRecord::RecordNotFound
		render nothing: true

		return
	end
end

app/controllers/company/base.rb
class Company::Base < ApplicationController
	before_action :set_company

	protected

	def set_company
		@company = Company.friendly.find(params[:company_id] || params[:id])
	rescue ActiveRecord::RecordNotFound
		flash[:danger] = t('messages.not_found', model: Company.model_name.human)
		redirect_back and return
	end

	def check_company_authorization!
		unless current_company == @company
			flash[:danger] = t('not_authorized')
			redirect_back and return
		end
	end
end

app/controllers/company/companies_controller.rb
class Company::CompaniesController < Company::Base
	before_action :set_company, only: [:show, :confirm]

	def new
		@company = Company.new
	end

	def create
		@company = Company.new company_params

		unless verify_recaptcha
			flash.now[:danger] = t('messages.validation_of_recatcha_failed')
			flash.delete :recaptcha_error
			render :new
			return
		end

		@company.generate_confirmation_token

		if @company.save
			CompanyMailer.confirmation_mail(@company).deliver_now

			flash[:success] = t('messages.sign_up_successful')
			redirect_to root_path
		else
			puts(@company.errors.messages)
			flash.now[:danger] = t('messages.unable_to_save')
			render :new
		end
	end

	def show
		if @company == current_company
			@products = @company.products.paginate(page: params[:page])
		else
			@products = @company.products.active.paginate(page: params[:page])
		end
	end

	## Non-RESTful method to confirm company accounts
	def confirm
		if @company.confirmation_token.present?
			if ActiveSupport::SecurityUtils.secure_compare(params[:confirmation_token], @company.confirmation_token)
				if @company.confirm
					flash[:success] = t('messages.account_confirmed')
				end

				redirect_to new_company_session_path
			else
				flash[:danger] = t('messages.invalid_confirmation_token')
				redirect_to root_path
			end
		else
			flash[:info] = t('messages.account_already_confirmed')
			redirect_to new_company_session_path
		end
	end

	protected

	def company_params
		params.require(:company).permit(:name, :email, :password, :password_confirmation, :street, :zip_code, :locality, :phone_number, :vat_number)
	end
end

app/controllers/company/password_reset_controller.rb
class Company::PasswordResetController < Company::Base
	before_action :set_company, only: [:edit, :update]
	before_action :verify_password_reset_token!, only: [:edit, :update]

	def new
		@company = Company.new
	end

	def create
		@company = Company.find_by email: params[:company][:email]

		if @company
			if @company.generate_password_reset_token && @company.save(validate: false) && CompanyMailer.password_reset_mail(@company).deliver_now
				flash[:success] = t('messages.password_reset_link_send')
				redirect_to root_path
			else
				flash[:danger] = t('messages.generic_error')
				redirect_back
			end
		else
			redirect_to new_company_password_path
		end
	end

	def edit
	end

	def update
		if @company.update company_password_params
			@company.update_attribute(:password_reset_token, nil)

			flash[:success] = t('messages.updated', model: Company.model_name.human)
			redirect_to new_company_session_path
		else
			flash[:danger] = t('messages.unable_to_save')
			redirect_back and return
		end
	end

	protected

	def verify_password_reset_token!
		if not @company.password_reset_token.present? && ActiveSupport::SecurityUtils.secure_compare(@company.password_reset_token, params[:reset_token])
			render :edit
			return
		end
	end

	def company_password_params
		params.require(:company).permit(:password, :password_confirmation)
	end
end

app/controllers/company/products_controller.rb
class Company::ProductsController < Company::Base
	include LocationsHelper
	include CountHelper

	before_action :set_product, only: [:show, :edit, :update, :destroy]
	before_action :check_company_authorization!, except: [:index, :show]
	before_action :check_if_product_limit_archived, only: [:new, :create]

	def index
		if @company == current_company
			@products = @company.products.paginate(page: params[:page])
		else
			@products = @company.products.active.paginate(page: params[:page])
		end
	end

	def new
		unless @company.remaining_products.nil?
			if @company.remaining_products <= 2
				flash[:warning] = t('messages.only_x_products_anymore', count: @company.remaining_products)
			end
		end

		@product = @company.products.new
	end

	def create
		@product = @company.products.new product_params

		if @product.save
			@company.decrement_product_counter
			@company.save

			flash[:success] = t('messages.created', model: Product.model_name.human)
			redirect_to [@company, @product]
		else
			render :new
		end
	end

	def show
		count_user(@product)

		@maps_hash = hash_for_maps(@product.company)
	end

	def edit
	end

	def update
		if @product.update(product_params)
			flash[:success] = t('messages.updated', model: Product.model_name.human)
			redirect_to [@company, @product]
		else
			render :edit
		end
	end

	def destroy
	end

	private

	def set_product
		if @company == current_company
			@product = @company.products.find(params[:id])
		else
			@product = @company.products.active.find(params[:id])
		end
	rescue ActiveRecord::RecordNotFound
		flash[:danger] = t('messages.not_found', model: Product.model_name.human)
		redirect_back and return
	end

	def product_params
		params.require(:product).permit(:name, :price, :status, :description, :order_link, :product_picture, :price_on_request)
	end

	def check_if_product_limit_archived
		unless @company.product_publishing_remaining?
			flash[:danger] = t('messages.product_limit_archived')
			redirect_back and return
		end
	end
end

app/controllers/company/sessions_controller.rb
class Company::SessionsController < ApplicationController
	def new
		@company = Company.new
	end

	def create
		@company = Company.find_by(email: params[:company][:email])

		if @company && @company.authenticate(params[:company][:password])
			if @company.confirmed?
				if params[:remember_me] == "true"
					cookies.permanent.signed[:company_id] = @company.id
				else
					cookies.signed[:company_id] = @company.id
				end

				flash[:success] = t('messages.signed_in')
				redirect_to root_path
			else
				flash[:danger] = t('messages.account_not_confirmed')
				redirect_back
			end
		else
			flash[:danger] = t('messages.invalid_credentials')
			redirect_back
		end
	end

	def destroy
		cookies.delete(:company_id)
		
		if not company_signed_in?
			flash[:success] = t('messages.logged_out')
			redirect_to root_path
		else
			flash[:danger] = t('messages.still_logged_in')
			redirect_to root_path
		end
	end
end

app/controllers/product/base.rb
class Product::Base < ApplicationController
end

app/views/company/products/_form.html.erb
<%= simple_form_for [@company, @product] do |f| %>
	<%= f.input :name %>
	<%= f.input :price_on_request, as: :boolean %>
	<%= f.input :price, required: true %>
	<%= f.input :description %>
	<%= f.input :status, collection: Product::STATUSES, include_blank: false, required: true %>
	<%= f.input :order_link %>
	<%= f.input :product_picture %>

	<%= f.button :submit %>
<% end %>

<script type="text/javascript">
	var priceOnRequestBox = $('input[name="product[price_on_request]"]');
	var priceField = $('input[name="product[price]"]');

	priceOnRequestBox.change(checkIfPriceIsOnRequest);

	function checkIfPriceIsOnRequest() {
		if (priceOnRequestBox.is(':checked')) {
			priceField.prop('disabled', true);
		} else {
			priceField.prop('disabled', false);
		}
	}

	$(function() {
		checkIfPriceIsOnRequest();
	});
</script>

app/views/company/products/edit.html.erb
<div class="col-md-offset-3 col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				<%= t('edit_model', model: Product.model_name.human) %>
			</h3>
		</div>
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/company/products/index.html.erb
<h1><%= t('resource_by_model', resource: Product.model_name.human(count: @products.count), model: @company.name) %></h1>

<% if @products.empty? %>
	<%= t('currently_no_products_available') %>
<% else %>
	<% @products.each do |product| %>
		<%= render 'product/products/wrapper', product: product %>
	<% end %>
<% end %>

app/views/company/products/new.html.erb
<div class="col-md-offset-3 col-md-6">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">
				<%= t('new_model', model: Product.model_name.human) %>
			</h3>
		</div>
		<div class="panel-body">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/company/products/show.html.erb
<% content_for :head do %>
	<%= tag :meta, property: "fb:app_id", content: ENV["FACEBOOK_APP_ID"] %>
	<%= tag :meta, property: "og:title", content: @product.name %>
	<%= tag :meta, property: "og:description", content: @product.description.present? ? @product.description : t('product_by', company: @company.name) %>
	<%= tag :meta, property: "og:type", content: "product" %>
	<%= tag :meta, property: "og:url", content: company_product_url(@company, @product) %>
	<%= tag :meta, property: "og:image", content: @product.product_picture.url %>
	<%= tag :meta, property: "og:locale", content: "de_DE" %>
	<%= tag :meta, property: "og:locale:alternate", content: "en_US" %>
	<%= tag :meta, property: "og:site_name", content: "Vendox" %>
	<%= tag :meta, property: "product:price:amount", content: @product.price if @product.price.present? %>
	<%= tag :meta, property: "product:price:currency", content: "EUR" if @product.price.present? %>
	<%= tag :meta, property: "product:sale_price:amount", content: @product.price if @product.price.present? %>
	<%= tag :meta, property: "product:sale_price:currency", content: "EUR" if @product.price.present? %>
	<%= tag :meta, property: "product:retailer_title", content: @company.name %>
	<%= tag :meta, property: "product:is_product_shareable", content: true %>

	<script type="application/ld+json">
	{
		"@context": "http://schema.org/",
		"@type": "Product",
		"name": "<%= @product.name %>",
		<% if @product.description.present? %>
		"description": "<%= @product.description %>",
		<% end %>
		<% if @product.price.present? %>
		"offers": {
			"@type": "Offer",
			"priceCurrency": "EUR",
			"price": "<%= @product.price %>"
		},
		<% end %>
		"image": "<%= @product.product_picture.url %>"
	}
	</script>
<% end %>

<% provide(:title, @product.name) %>

<div class="panel panel-default">
	<div class="panel-body">
		<div class="col-md-4">
			<%= image_tag @product.product_picture, width: '100%', class: 'img-thumbnail' %>

			<% if @product.description.present? %>
				<h3>
					<%= t('description') %>
				</h3>

				<p>
					<%= h(@product.description).gsub(/\n/, '<br>').html_safe %>
				</p>
			<% end %>
		</div>

		<div class="col-md-8 text-center">
			<h1>
				<%= @product.name %>
				<small>
					<%= t('by_model', model: link_to(@company.name, @company)).html_safe %>
					<% if current_user_session && current_user_session.coordinates.present? %>
						<br><%= @product.distance_to(current_user_session.coordinates).round(2) %> km <%= t('away') %>
					<% end %>
				</small>
			</h1>
			<% if @product.order_link.present? %>
				<%= link_to t('order'), @product.order_link, class: 'btn btn-primary', target: '_blank' %>
			<% end %>

			<p>
				<h3>
					<% if @product.price_on_request %>
						<%= t('price_on_request') %>
					<% else %>
						<%= number_to_currency @product.price, locale: :de %>
					<% end %>
				</h3>
				<%= @company.address %><br>

				<span class="glyphicon glyphicon-earphone"></span> <%= @company.phone_number %>&nbsp;&nbsp;&nbsp;
				<span class="glyphicon glyphicon-envelope"></span> <%= @company.email %>
			</p>

			<p>
			<div class="fb-like" data-href="<%= company_product_url(@company, @product) %>" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
			<div class="fb-send" data-href="<%= company_product_url(@company, @product) %>"></div>
			</p>

			<div class="thumbnail" id="map" style="height: 400px"></div>
		</div>
	</div>
</div>

<script type="text/javascript">
	buildMap(<%=raw @maps_hash.to_json %>, setZoom = true);
</script>