config/routes.rb
Rails.application.routes.draw do
	root 'welcome#index'

	scope "(:locale)", locale: /en|de/ do
		get 'position' => 'application#set_user_position'
		get 'imprint' => 'welcome#imprint'
		get 'about' => 'welcome#about'

		resources :products, module: :product, only: [:index]

		resources :feedbacks, only: [:new, :create]
		
		resources :companies, only: [:new, :create, :show], module: :company do
			resources :products
			get "confirm/:confirmation_token" => "companies#confirm", as: :confirm
			resources :password, only: [:update, :edit], controller: :password_reset, param: :reset_token
		end

		namespace :company, path: :companies do
			resources :sessions, only: [:new, :create]
			delete "sessions" => "sessions#destroy"
			resources :password, only: [:new], controller: :password_reset
			post 'password' => "password_reset#create", as: :password_reset_create
		end

		get ':id' => 'company/companies#show'
	end

	namespace 'api', defaults: { format: :json } do
		namespace 'v1' do
			resources :companies, module: :company, only: [:index, :show] do 
				resources :products, only: [:index, :show]
			end

			resources :products, module: :product, only: [:index]

			namespace :user, path: :users do
				resources :sessions, only: [:create]
				get 'session' => "sessions#show"
				resources :positions, only: [:index, :create, :show]
			end
		end

		namespace 'v2' do
			resources :companies, module: :company, only: [:index, :show] do 
				resources :products, only: [:index, :show]
			end

			resources :products, module: :product, only: [:index]

			namespace :user, path: :users do
				resources :sessions, only: [:create]
				get 'session' => "sessions#show"
				resources :positions, only: [:index, :create, :show]
			end
		end
	end

end

app/views/shared/_footer.html.erb
<div class="col-md-12 footer text-center">
	<div class="wrapper-location">
		<span class="current-location-info">
			<%= t('your_current_location_is') %>
			<strong>
				<span id="span-user-address">
				</span>
			</strong>
			| <%= link_to t('renew_location'), "#", class: 'lnk-location-renew' %>
		</span>
	</div>

	<br>

	<p>
		<%= link_to t('imprint'), imprint_path %>
	</p>
</div>

app/views/shared/_header.html.erb
<%
	if not defined? subtitle
		subtitle = false
	end
%>

<div class="page-header">
	<h1>
		<%= title %>
		<% if subtitle %>
			<small>
				<%= subtitle %>
			</small>
		<% end %>
	</h1>
</div>

app/views/shared/_messages.html.erb
<div class="container">
	<% flash.each do |type, message| %>
		<div class="alert alert-<%= flash_class(type) %> alert-dismissible">
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">
					&times;
				</span>
			</button>
		
			<%= message %>
		</div>
	<% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to root_path, class: "navbar-brand" do %>
				<%= image_tag "/logo/navbar.png" %>
			<% end %>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav">
				<% if company_signed_in? %>
					<li class="dropdown">
						<%= link_to [current_company, :products], class: 'dropdown-toggle', :'data-toggle' => 'dropdown', :'aria-expanded' => 'false' do %>
							<%= Product.model_name.human(count: 2) %> <span class="caret"></span>
						<% end %>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to t('all'), [current_company, :products] %></li>
							<li><%= link_to t('new'), [:new, current_company, :product] %></li>
		           		</ul>
					</li>
				<% end %>
				<li><%= link_to t('browse_through', model: Product.model_name.human(count: 2)), products_path %></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if company_signed_in? %>
					<li><%= link_to current_company.name, current_company %></li>
					<li><%= link_to t('logout'), company_sessions_path, method: :delete %></li>
				<% end %>
				<% unless company_signed_in? %>
					<li><%= link_to t("navbar_feedback_text.text_#{rand(3)}"), new_feedback_path %></li>
				<% end %>
				<li><%= link_to "Feedback", new_feedback_path %></li>
				<li>
					<% if I18n.locale == :de %>
						<%= link_to "EN", controller: controller_name, action: action_name, locale: :en %>
					<% else %>
						<%= link_to "DE", controller: controller_name, action: action_name, locale: :de %>
					<% end %>
				</li>
				<li>
					<%= link_to "https://www.facebook.com/vendoxfinder", :target => "_blank" do %>
						<%= image_tag "navbar/facebook.png", id: 'img-fb-navbar' %>
					<% end %>
				</li>
			</ul>
		</div><!--/.nav-collapse -->
	</div>
</nav>